CREATE TABLE Alunos (
	Matricla NVARCHAR(100) PRIMARY KEY,
	Nome NVARCHAR(100) NOT NULL,
	DataNascimento DATE NOT NULL,
	Turma NVARCHAR(50) NOT NULL,
	Email NVARCHAR(100) UNIQUE NOT NULL,
	Telefone NVARCHAR(15),
	Status NVARCHAR(20) NOT NULL DEFAULT 'Ativo',
	DataCadastro DATETIME NOT NULL DEFAULT GETDATE(),
	DataAtualizacao DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT CHK_Status CHECK (Status IN ('Ativo', 'Inativo', 'Suspenso'))
);